In [1]:
import pandas as pd
import sqlite3

from nba_api.stats.endpoints import leaguegamefinder
from nba_api.stats.static import teams

In [3]:
with sqlite3.connect('data/games.db') as con:
    games = pd.read_sql(sql='SELECT * FROM games', con=con)

games

,game_id,event,season,date,status,home_team,away_team,home_score,away_score,home_2PA,...,home_BLK,away_BLK,home_STL,away_STL,home_TOV,away_TOV,home_PF,away_PF,home_odds,away_odds
0,vDxeS9an,NBA,1993,04.11.1993 22:00,Finished,Utah Jazz,Dallas Mavericks,102,86,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN
1,SxZjTkpt,NBA,1993,04.11.1993 22:00,Finished,San Antonio Spurs,Golden State Warriors,91,85,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN
2,SbWrLhhJ,NBA,1993,04.11.1993 22:00,Finished,Sacramento Kings,Denver Nuggets,109,100,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN
3,l8XvMYxD,NBA,1993,04.11.1993 22:00,Finished,Philadelphia 76ers,Washington Wizards,94,82,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN
4,KYSzNEN6,NBA,1993,04.11.1993 22:00,Finished,Miami Heat,Orlando Magic,96,116,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36526,d03RaCUh,NBA,2021,20.11.2021 21:30,Finished,Atlanta Hawks,Charlotte Hornets,115,105,48.0,...,6.0,2.0,7.0,6.0,12.0,11.0,22.0,22.0,1.64,3.80
36527,nkdvcAEB,NBA,2021,20.11.2021 22:00,Finished,Minnesota Timberwolves,Memphis Grizzlies,138,95,50.0,...,6.0,5.0,12.0,7.0,13.0,16.0,26.0,24.0,1.64,2.20
36528,UD1Zcja5,NBA,2021,20.11.2021 22:00,Finished,Milwaukee Bucks,Orlando Magic,117,108,42.0,...,5.0,3.0,6.0,5.0,14.0,10.0,18.0,24.0,1.64,8.25
36529,IyJBv2bp,NBA,2021,21.11.2021 00:00,Finished,Sacramento Kings,Utah Jazz,105,123,60.0,...,5.0,2.0,8.0,5.0,8.0,13.0,14.0,16.0,3.8,8.25
36530,QuerdUTH,NBA,2021,21.11.2021 00:00,Finished,Portland Trail Blazers,Philadelphia 76ers,118,111,46.0,...,7.0,4.0,6.0,7.0,13.0,12.0,21.0,24.0,3.8,3.80

In [4]:
games.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36531 entries, 0 to 36530
Data columns (total 37 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   game_id     36531 non-null  object
 1   event       36531 non-null  object
 2   season      36531 non-null  int64
 3   date        36531 non-null  object
 4   status      36531 non-null  object
 5   home_team   36531 non-null  object
 6   away_team   36531 non-null  object
 7   home_score  36531 non-null  int64
 8   away_score  36531 non-null  int64
 9   home_2PA    12636 non-null  float64
 10  away_2PA    12636 non-null  float64
 11  home_2PM    12636 non-null  float64
 12  away_2PM    12636 non-null  float64
 13  home_3PA    12636 non-null  float64
 14  away_3PA    12636 non-null  float64
 15  home_3PM    12636 non-null  float64
 16  away_3PM    12636 non-null  float64
 17  home_FTA    12636 non-null  float64
 18  away_FTA    12636 non-null  float64
 19  home_FTM    12636 non-null  float64
 20  away_FTM    12636 non-null  float64
 21  home_OREB   12636 non-null  float64
 22  away_OREB   12636 non-null  float64
 23  home_DREB   12636 non-null  float64
 24  away_DREB   12636 non-null  float64
 25  home_AST    12636 non-null  float64
 26  away_AST    12636 non-null  float64
 27  home_BLK    12636 non-null  float64
 28  away_BLK    12636 non-null  float64
 29  home_STL    11214 non-null  float64
 30  away_STL    11214 non-null  float64
 31  home_TOV    12636 non-null  float64
 32  away_TOV    12636 non-null  float64
 33  home_PF     12636 non-null  float64
 34  away_PF     12636 non-null  float64
 35  home_odds   18008 non-null  object
 36  away_odds   18006 non-null  float64
dtypes: float64(27), int64(3), object(7)
memory usage: 10.3+ MB

In [6]:
games['date'] = pd.to_datetime(games['date'])

In [10]:
games.sort_values('date', ascending=False).head(10)
games['date'].

AttributeError: 'Series' object has no attribute 'day'

In [64]:
games['home_FGA'] == games['home_2PA'] + games['home_3PA']

0       True
1       True
2       True
3       True
4       True
        ...
1238    True
1239    True
1240    True
1241    True
1242    True
Length: 36531, dtype: bool

In [30]:
teams[0]

{'id': 1610612737,
 'full_name': 'Atlanta Hawks',
 'abbreviation': 'ATL',
 'nickname': 'Hawks',
 'city': 'Atlanta',
 'state': 'Atlanta',
 'year_founded': 1949}

In [38]:
lakers = [team for team in teams if team['full_name'] == 'Los Angeles Lakers']
lakers_id = lakers[0]['id']
lakers

[{'id': 1610612747,
  'full_name': 'Los Angeles Lakers',
  'abbreviation': 'LAL',
  'nickname': 'Lakers',
  'city': 'Los Angeles',
  'state': 'California',
  'year_founded': 1948}]

In [3]:
gamefinder = leaguegamefinder.LeagueGameFinder(team_id_nullable=1610612747)

In [4]:
games = gamefinder.get_data_frames()[0]
games

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,PTS,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PLUS_MINUS
0,22021,1610612747,LAL,Los Angeles Lakers,0022100264,2021-11-23,LAL @ NYK,L,241,100,...,0.700,13,37,50,23,8,3,12,17,-6.0
1,22021,1610612747,LAL,Los Angeles Lakers,0022100249,2021-11-21,LAL @ DET,W,240,121,...,0.778,12,39,51,29,7,8,13,21,5.0
2,22021,1610612747,LAL,Los Angeles Lakers,0022100232,2021-11-19,LAL @ BOS,L,241,108,...,0.750,7,26,33,20,5,6,12,29,-22.0
3,22021,1610612747,LAL,Los Angeles Lakers,0022100219,2021-11-17,LAL @ MIL,L,241,102,...,0.833,11,37,48,24,8,4,13,19,-7.0
4,22021,1610612747,LAL,Los Angeles Lakers,0022100209,2021-11-15,LAL vs. CHI,L,239,103,...,0.806,8,35,43,19,10,5,17,15,-18.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3677,21983,1610612747,LAL,Los Angeles Lakers,0028300066,1983-11-08,LAL @ DEN,W,240,133,...,0.917,22,31,53,30,11,8,23,31,NaN
3678,21983,1610612747,LAL,Los Angeles Lakers,0028300053,1983-11-05,LAL @ DAL,L,240,102,...,0.667,18,23,41,29,7,8,20,27,NaN
3679,21983,1610612747,LAL,Los Angeles Lakers,0028300035,1983-11-02,LAL @ SDC,L,240,106,...,0.760,16,33,49,29,14,7,24,24,NaN
3680,21983,1610612747,LAL,Los Angeles Lakers,0028300010,1983-10-29,LAL @ UTH,W,240,120,...,0.718,29,31,60,25,10,10,20,41,NaN
3681,21983,1610612747,LAL,Los Angeles Lakers,0028300002,1983-10-28,LAL @ KCK,W,240,117,...,0.760,9,29,38,22,6,5,17,16,NaN

In [5]:
games.dtypes.to_dict()

{'SEASON_ID': dtype('O'),
 'TEAM_ID': dtype('int64'),
 'TEAM_ABBREVIATION': dtype('O'),
 'TEAM_NAME': dtype('O'),
 'GAME_ID': dtype('O'),
 'GAME_DATE': dtype('O'),
 'MATCHUP': dtype('O'),
 'WL': dtype('O'),
 'MIN': dtype('int64'),
 'PTS': dtype('int64'),
 'FGM': dtype('int64'),
 'FGA': dtype('int64'),
 'FG_PCT': dtype('float64'),
 'FG3M': dtype('int64'),
 'FG3A': dtype('int64'),
 'FG3_PCT': dtype('float64'),
 'FTM': dtype('int64'),
 'FTA': dtype('int64'),
 'FT_PCT': dtype('float64'),
 'OREB': dtype('int64'),
 'DREB': dtype('int64'),
 'REB': dtype('int64'),
 'AST': dtype('int64'),
 'STL': dtype('int64'),
 'BLK': dtype('int64'),
 'TOV': dtype('int64'),
 'PF': dtype('int64'),
 'PLUS_MINUS': dtype('float64')}

In [6]:
games.columns.to_list()

['SEASON_ID',
 'TEAM_ID',
 'TEAM_ABBREVIATION',
 'TEAM_NAME',
 'GAME_ID',
 'GAME_DATE',
 'MATCHUP',
 'WL',
 'MIN',
 'PTS',
 'FGM',
 'FGA',
 'FG_PCT',
 'FG3M',
 'FG3A',
 'FG3_PCT',
 'FTM',
 'FTA',
 'FT_PCT',
 'OREB',
 'DREB',
 'REB',
 'AST',
 'STL',
 'BLK',
 'TOV',
 'PF',
 'PLUS_MINUS']

In [8]:
games.head(1).to_dict()

{'SEASON_ID': {0: '22021'},
 'TEAM_ID': {0: 1610612747},
 'TEAM_ABBREVIATION': {0: 'LAL'},
 'TEAM_NAME': {0: 'Los Angeles Lakers'},
 'GAME_ID': {0: '0022100264'},
 'GAME_DATE': {0: '2021-11-23'},
 'MATCHUP': {0: 'LAL @ NYK'},
 'WL': {0: 'L'},
 'MIN': {0: 241},
 'PTS': {0: 100},
 'FGM': {0: 34},
 'FGA': {0: 91},
 'FG_PCT': {0: 0.374},
 'FG3M': {0: 11},
 'FG3A': {0: 36},
 'FG3_PCT': {0: 0.306},
 'FTM': {0: 21},
 'FTA': {0: 30},
 'FT_PCT': {0: 0.7},
 'OREB': {0: 13},
 'DREB': {0: 37},
 'REB': {0: 50},
 'AST': {0: 23},
 'STL': {0: 8},
 'BLK': {0: 3},
 'TOV': {0: 12},
 'PF': {0: 17},
 'PLUS_MINUS': {0: -6.0}}

In [9]:
sorted(games['SEASON_ID'].unique(), reverse=True)

['52020',
 '42020',
 '42019',
 '42012',
 '42011',
 '42010',
 '42009',
 '42008',
 '42007',
 '42006',
 '42005',
 '42003',
 '42002',
 '42001',
 '42000',
 '41999',
 '41998',
 '41997',
 '41996',
 '41995',
 '41994',
 '41992',
 '41991',
 '41990',
 '41989',
 '41988',
 '41987',
 '41986',
 '41985',
 '41984',
 '41983',
 '22021',
 '22020',
 '22019',
 '22018',
 '22017',
 '22016',
 '22015',
 '22014',
 '22013',
 '22012',
 '22011',
 '22010',
 '22009',
 '22008',
 '22007',
 '22006',
 '22005',
 '22004',
 '22003',
 '22002',
 '22001',
 '22000',
 '21999',
 '21998',
 '21997',
 '21996',
 '21995',
 '21994',
 '21993',
 '21992',
 '21991',
 '21990',
 '21989',
 '21988',
 '21987',
 '21986',
 '21985',
 '21984',
 '21983',
 '12021',
 '12020',
 '12019',
 '12018',
 '12017',
 '12016',
 '12015',
 '12014',
 '12013',
 '12012',
 '12011',
 '12010',
 '12009',
 '12008',
 '12007',
 '12006',
 '12005',
 '12004']

In [93]:
games[games.SEASON_ID == '22018'].tail(15)

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,PTS,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PLUS_MINUS
297,22018,1610612747,LAL,Los Angeles Lakers,0021800066,2018-10-25,LAL vs. DEN,W,240,121,...,0.826,9,33,42,27,13,3,13,19,7.0
298,22018,1610612747,LAL,Los Angeles Lakers,0021800060,2018-10-24,LAL @ PHX,W,239,131,...,0.739,11,32,43,34,13,5,8,19,18.0
299,22018,1610612747,LAL,Los Angeles Lakers,0021800048,2018-10-22,LAL vs. SAS,L,266,142,...,0.692,13,39,52,33,5,6,15,29,-1.0
300,22018,1610612747,LAL,Los Angeles Lakers,0021800035,2018-10-20,LAL vs. HOU,L,240,115,...,0.611,9,35,44,28,8,10,10,21,-9.0
301,22018,1610612747,LAL,Los Angeles Lakers,0021800016,2018-10-18,LAL @ POR,L,239,119,...,0.759,8,38,46,23,10,6,15,26,-9.0
308,22018,1610612747,LAL,Los Angeles Lakers,1521800082,2018-07-17,LAL vs. POR,L,199,73,...,0.762,4,27,31,11,5,1,15,25,-18.2
309,22018,1610612747,LAL,Los Angeles Lakers,1521800080,2018-07-16,LAL vs. CLE,W,220,112,...,0.708,11,25,36,17,5,3,11,28,0.0
310,22018,1610612747,LAL,Los Angeles Lakers,1521800076,2018-07-15,LAL vs. DET,W,199,101,...,0.842,12,32,44,24,4,5,12,23,23.4
311,22018,1610612747,LAL,Los Angeles Lakers,1521800059,2018-07-12,LAL vs. LAC,W,199,82,...,0.905,5,32,37,20,8,4,18,22,14.6
312,22018,1610612747,LAL,Los Angeles Lakers,1521800045,2018-07-10,LAL @ NYK,W,200,109,...,0.750,9,26,35,19,9,6,11,23,2.4
313,22018,1610612747,LAL,Los Angeles Lakers,1521800030,2018-07-08,LAL @ CHI,W,198,69,...,0.647,10,34,44,14,9,2,8,17,9.0
314,22018,1610612747,LAL,Los Angeles Lakers,1521800020,2018-07-07,LAL vs. PHI,W,201,96,...,0.720,12,32,44,17,6,4,19,23,17.0
315,22018,1610612747,LAL,Los Angeles Lakers,1321800005,2018-07-05,LAL @ GSW,L,240,71,...,0.476,9,38,47,16,6,7,23,19,-6.0
316,22018,1610612747,LAL,Los Angeles Lakers,1321800003,2018-07-03,LAL vs. MIA,L,241,74,...,0.467,12,24,36,14,7,7,20,27,-15.0
317,22018,1610612747,LAL,Los Angeles Lakers,1321800002,2018-07-02,LAL @ SAC,L,239,93,...,0.864,8,24,32,22,9,4,14,23,-5.0

In [94]:
games[games.SEASON_ID == '12018']

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,PTS,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PLUS_MINUS
302,12018,1610612747,LAL,Los Angeles Lakers,0011800079,2018-10-12,LAL @ GSW,W,241,119,...,0.732,9,41,50,29,6,4,22,24,18.0
303,12018,1610612747,LAL,Los Angeles Lakers,0011800065,2018-10-10,LAL vs. GSW,W,239,123,...,0.826,9,36,45,28,13,5,19,27,10.0
304,12018,1610612747,LAL,Los Angeles Lakers,0011800042,2018-10-06,LAL vs. LAC,L,240,87,...,0.636,11,37,48,24,8,7,20,28,-16.0
305,12018,1610612747,LAL,Los Angeles Lakers,0011800027,2018-10-04,LAL vs. SAC,W,240,128,...,0.727,7,41,48,19,6,6,18,25,7.0
306,12018,1610612747,LAL,Los Angeles Lakers,0011800020,2018-10-02,LAL vs. DEN,L,242,111,...,0.789,3,35,38,28,12,7,23,30,-2.0
307,12018,1610612747,LAL,Los Angeles Lakers,0011800010,2018-09-30,LAL vs. DEN,L,240,107,...,0.731,7,30,37,26,9,7,21,31,-17.0

In [92]:
games[games.SEASON_ID == '22018']

,SEASON_ID,TEAM_ID,TEAM_ABBREVIATION,TEAM_NAME,GAME_ID,GAME_DATE,MATCHUP,WL,MIN,PTS,...,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PLUS_MINUS
220,22018,1610612747,LAL,Los Angeles Lakers,0021801219,2019-04-09,LAL vs. POR,L,240,101,...,0.647,17,34,51,29,6,6,17,19,-3.0
221,22018,1610612747,LAL,Los Angeles Lakers,0021801208,2019-04-07,LAL vs. UTA,W,240,113,...,0.667,16,33,49,28,5,5,16,21,4.0
222,22018,1610612747,LAL,Los Angeles Lakers,0021801192,2019-04-05,LAL @ LAC,W,240,122,...,0.815,14,41,55,28,8,10,14,24,5.0
223,22018,1610612747,LAL,Los Angeles Lakers,0021801179,2019-04-04,LAL vs. GSW,L,240,90,...,0.571,18,44,62,25,10,7,18,10,-18.0
224,22018,1610612747,LAL,Los Angeles Lakers,0021801161,2019-04-02,LAL @ OKC,L,240,103,...,0.700,4,35,39,26,7,2,21,25,-16.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
313,22018,1610612747,LAL,Los Angeles Lakers,1521800030,2018-07-08,LAL @ CHI,W,198,69,...,0.647,10,34,44,14,9,2,8,17,9.0
314,22018,1610612747,LAL,Los Angeles Lakers,1521800020,2018-07-07,LAL vs. PHI,W,201,96,...,0.720,12,32,44,17,6,4,19,23,17.0
315,22018,1610612747,LAL,Los Angeles Lakers,1321800005,2018-07-05,LAL @ GSW,L,240,71,...,0.476,9,38,47,16,6,7,23,19,-6.0
316,22018,1610612747,LAL,Los Angeles Lakers,1321800003,2018-07-03,LAL vs. MIA,L,241,74,...,0.467,12,24,36,14,7,7,20,27,-15.0
317,22018,1610612747,LAL,Los Angeles Lakers,1321800002,2018-07-02,LAL @ SAC,L,239,93,...,0.864,8,24,32,22,9,4,14,23,-5.0

In [114]:
games[games.GAME_ID == '1521800082'].to_dict()

{'SEASON_ID': {308: '22018'},
 'TEAM_ID': {308: 1610612747},
 'TEAM_ABBREVIATION': {308: 'LAL'},
 'TEAM_NAME': {308: 'Los Angeles Lakers'},
 'GAME_ID': {308: '1521800082'},
 'GAME_DATE': {308: '2018-07-17'},
 'MATCHUP': {308: 'LAL vs. POR'},
 'WL': {308: 'L'},
 'MIN': {308: 199},
 'PTS': {308: 73},
 'FGM': {308: 27},
 'FGA': {308: 69},
 'FG_PCT': {308: 0.391},
 'FG3M': {308: 3},
 'FG3A': {308: 21},
 'FG3_PCT': {308: 0.143},
 'FTM': {308: 16},
 'FTA': {308: 21},
 'FT_PCT': {308: 0.762},
 'OREB': {308: 4},
 'DREB': {308: 27},
 'REB': {308: 31},
 'AST': {308: 11},
 'STL': {308: 5},
 'BLK': {308: 1},
 'TOV': {308: 15},
 'PF': {308: 25},
 'PLUS_MINUS': {308: -18.2}}