In [75]:
import pandas as pd
import sqlite3

In [76]:
with sqlite3.connect('data/games.db') as con:
    games = pd.read_sql(sql='SELECT * FROM games', con=con)

games

,game_id,event,season,date,status,home_team,away_team,home_score,away_score,home_2PA,...,home_BLK,away_BLK,home_STL,away_STL,home_TOV,away_TOV,home_PF,away_PF,home_odds,away_odds
0,vDxeS9an,NBA,1993,04.11.1993 22:00,Finished,Utah Jazz,Dallas Mavericks,102,86,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN
1,SxZjTkpt,NBA,1993,04.11.1993 22:00,Finished,San Antonio Spurs,Golden State Warriors,91,85,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN
2,SbWrLhhJ,NBA,1993,04.11.1993 22:00,Finished,Sacramento Kings,Denver Nuggets,109,100,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN
3,l8XvMYxD,NBA,1993,04.11.1993 22:00,Finished,Philadelphia 76ers,Washington Wizards,94,82,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN
4,KYSzNEN6,NBA,1993,04.11.1993 22:00,Finished,Miami Heat,Orlando Magic,96,116,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36526,d03RaCUh,NBA,2021,20.11.2021 21:30,Finished,Atlanta Hawks,Charlotte Hornets,115,105,48.0,...,6.0,2.0,7.0,6.0,12.0,11.0,22.0,22.0,1.64,3.80
36527,nkdvcAEB,NBA,2021,20.11.2021 22:00,Finished,Minnesota Timberwolves,Memphis Grizzlies,138,95,50.0,...,6.0,5.0,12.0,7.0,13.0,16.0,26.0,24.0,1.64,2.20
36528,UD1Zcja5,NBA,2021,20.11.2021 22:00,Finished,Milwaukee Bucks,Orlando Magic,117,108,42.0,...,5.0,3.0,6.0,5.0,14.0,10.0,18.0,24.0,1.64,8.25
36529,IyJBv2bp,NBA,2021,21.11.2021 00:00,Finished,Sacramento Kings,Utah Jazz,105,123,60.0,...,5.0,2.0,8.0,5.0,8.0,13.0,14.0,16.0,3.8,8.25
36530,QuerdUTH,NBA,2021,21.11.2021 00:00,Finished,Portland Trail Blazers,Philadelphia 76ers,118,111,46.0,...,7.0,4.0,6.0,7.0,13.0,12.0,21.0,24.0,3.8,3.80

In [79]:
games = games.dropna()
games = games[games['event'] == 'NBA']
games = games[games['season'] < 2021]
games = games[games['home_odds'] != '-']
games = games[games.home_odds != games.away_odds]
games['home_team'] = games['home_team'].str.strip()
games['away_team'] = games['away_team'].str.strip()
games['date'] = pd.to_datetime(games['date']) - pd.Timedelta('02:00:00')

games

,game_id,event,season,date,status,home_team,away_team,home_score,away_score,home_2PA,...,home_BLK,away_BLK,home_STL,away_STL,home_TOV,away_TOV,home_PF,away_PF,home_odds,away_odds
25406,ALIdkw5Q,NBA,2013,2014-04-16 19:30:00,Finished,Denver Nuggets,Golden State Warriors,112,116,50.0,...,4.0,4.0,4.0,12.0,19.0,14.0,28.0,23.0,1.27,4.25
25407,x8KliazE,NBA,2013,2014-04-16 19:30:00,Finished,Portland Trail Blazers,Los Angeles Clippers,110,104,75.0,...,2.0,4.0,5.0,4.0,10.0,8.0,23.0,20.0,1.27,2.35
25408,GbJhjJkK,NBA,2013,2014-04-16 19:30:00,Finished,Sacramento Kings,Phoenix Suns,99,104,67.0,...,3.0,5.0,8.0,9.0,17.0,11.0,20.0,21.0,2.25,2.35
25409,8zNdWcbl,NBA,2013,2014-04-16 17:00:00,Finished,Boston Celtics,Washington Wizards,102,118,54.0,...,1.0,2.0,8.0,6.0,13.0,12.0,16.0,20.0,4,2.35
25411,lQ8HjEn6,NBA,2013,2014-04-16 17:00:00,After Overtime,Memphis Grizzlies,Dallas Mavericks,106,105,68.0,...,1.0,4.0,7.0,11.0,17.0,13.0,16.0,23.0,4,2.35
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36122,fHlfbd76,NBA,2020,2021-05-16 18:00:00,Finished,Portland Trail Blazers,Denver Nuggets,132,116,44.0,...,6.0,2.0,3.0,8.0,14.0,6.0,16.0,20.0,6.75,3.40
36123,lKon0Ixf,NBA,2020,2021-05-16 18:00:00,Finished,Oklahoma City Thunder,Los Angeles Clippers,117,112,68.0,...,12.0,3.0,1.0,8.0,15.0,3.0,11.0,14.0,6.75,1.29
36124,hhhw2v8s,NBA,2020,2021-05-16 18:00:00,Finished,New Orleans Pelicans,Los Angeles Lakers,98,110,52.0,...,5.0,5.0,4.0,14.0,21.0,9.0,18.0,16.0,4.5,1.29
36125,jq6B6KaQ,NBA,2020,2021-05-16 18:00:00,Finished,Minnesota Timberwolves,Dallas Mavericks,136,121,50.0,...,4.0,5.0,11.0,5.0,9.0,16.0,22.0,19.0,4.5,1.29
36126,tEOKqchD,NBA,2020,2021-05-16 18:00:00,Finished,Chicago Bulls,Milwaukee Bucks,118,112,55.0,...,8.0,5.0,8.0,13.0,16.0,11.0,20.0,16.0,4.5,1.37

In [80]:
games = games[['home_score', 'away_score', 'home_odds', 'away_odds']]
games

       home_score  away_score home_odds  away_odds
25406         112         116      1.27       4.25
25407         110         104      1.27       2.35
25408          99         104      2.25       2.35
25409         102         118         4       2.35
25411         106         105         4       2.35
...           ...         ...       ...        ...
36122         132         116      6.75       3.40
36123         117         112      6.75       1.29
36124          98         110       4.5       1.29
36125         136         121       4.5       1.29
36126         118         112       4.5       1.37

[9392 rows x 4 columns]

In [81]:
games['score'] = games['home_score'] - games['away_score']
games['home_odds'] = pd.to_numeric(games['home_odds'])
games['odds'] = games['home_odds'] - games['away_odds']

<ipython-input-81-38fc7d452abd>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  games['score'] = games['home_score'] - games['away_score']
<ipython-input-81-38fc7d452abd>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  games['home_odds'] = pd.to_numeric(games['home_odds'])
<ipython-input-81-38fc7d452abd>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  games['odds'] = games['home_odds'] - games['away_odds']

In [105]:
games

       home_score  away_score  home_odds  away_odds  score  odds  result
25406         112         116       1.27       4.25     -4 -2.98       0
25407         110         104       1.27       2.35      6 -1.08       1
25408          99         104       2.25       2.35     -5 -0.10       0
25409         102         118       4.00       2.35    -16  1.65       0
25411         106         105       4.00       2.35      1  1.65       1
...           ...         ...        ...        ...    ...   ...     ...
36122         132         116       6.75       3.40     16  3.35       1
36123         117         112       6.75       1.29      5  5.46       1
36124          98         110       4.50       1.29    -12  3.21       0
36125         136         121       4.50       1.29     15  3.21       1
36126         118         112       4.50       1.37      6  3.13       1

[9392 rows x 7 columns]

In [103]:
games['result'] = (games['score'] > 0).astype(int)

<ipython-input-103-64fd266c6809>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  games['result'] = (games['score'] > 0).astype(int)

In [104]:
games.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 9392 entries, 25406 to 36126
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   home_score  9392 non-null   int64
 1   away_score  9392 non-null   int64
 2   home_odds   9392 non-null   float64
 3   away_odds   9392 non-null   float64
 4   score       9392 non-null   int64
 5   odds        9392 non-null   float64
 6   result      9392 non-null   int64
dtypes: float64(3), int64(4)
memory usage: 587.0 KB

In [125]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import SGDClassifier

In [126]:
x = games.odds
y = games.result

x_train, x_test, y_train, y_test = train_test_split(x, y, random_state=42)

In [128]:
sgd = SGDClassifier()

In [132]:
sgd.fit(pd.DataFrame(x_train), y_train)

SGDClassifier()

In [133]:
score = sgd.score(pd.DataFrame(x_test), pd.DataFrame(y_test))
score

0.5357751277683135